USE customer_shoping_behviour_analysis;
SELECT * FROM mytable LIMIT 5;

  -- Q1. What is the total revenue generated by male vs. female customers?
 SELECT 
    gender, SUM(purchased_amount) AS revenue
FROM
    mytable
GROUP BY gender;

 -- Q2. Which customers used a discount but still spent more than the average purchase amount?
 select customer_id, purchased_amount
 from mytable
 where discount_applied = 'Yes' and purchased_amount >= (select AVG(purchased_amount) from mytable);
 
 -- Q3. Which are the top 5 products with the highest average review ratings?
select item_purchased, AVG(review_rating) as 'Average Product Rating'
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;
 
 -- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
avg(purchased_amount)
from mytable
where shipping_type in ('Standard', 'Express')
group by shipping_type;
 
 -- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
 select subscription_status, 
 COUNT(customer_id) as total_customers,
 avg(purchased_amount) as avg_spent,
 sum(purchased_amount) as total_revenue
 from mytable
 group by subscription_status
 order by avg_spent, total_revenue desc;
 
 -- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;
 
 -- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 THEN 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
end as 'customer_segment'
from mytable
)
select customer_segment, count(*) as 'number of customer'
from customer_type
group by customer_segment;
 
 -- Q8. What are the top 3 most purchased products within each category?
with item_counts as ( 
select category, item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from mytable
group by category, item_purchased
)
select category, item_purchased, item_rank, total_orders
from item_counts
where item_rank <= 3;
 
 -- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5
group by subscription_status;
 
 
 -- Q10. What is the revenue contribution of each age group?
 select age_group,
 sum(purchased_amount) as total_revenue
 from mytable
 group by age_group
 order by total_revenue desc;